"""create trip table

Revision ID: b3ed22948477
Revises: b84543f0c685
Create Date: 2026-03-15 10:22:14.321195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3ed22948477'
down_revision: Union[str, Sequence[str], None] = 'b84543f0c685'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('description', sa.String(), nullable=True))
    op.alter_column('trips', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('trips', 'descriptions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('descriptions', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('trips', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('trips', 'description')
    # ### end Alembic commands ###
