"""create trip tables

Revision ID: b84543f0c685
Revises: 
Create Date: 2026-03-13 08:39:38.442759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b84543f0c685'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('location', sa.String(), nullable=True))
    op.add_column('trips', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('trips_user_id_fkey'), 'trips', type_='foreignkey')
    op.create_foreign_key(None, 'trips', 'users', ['owner_id'], ['id'])
    op.drop_column('trips', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.create_foreign_key(op.f('trips_user_id_fkey'), 'trips', 'users', ['user_id'], ['id'])
    op.drop_column('trips', 'owner_id')
    op.drop_column('trips', 'location')
    # ### end Alembic commands ###
